server:
  port: ${PORT:8080}
  shutdown: graceful
spring:
  application:
    name: account-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI:mongodb://localhost:27017/account-service}
  cloud:
    stream:
      bindings:
        accountCreated-out-0:
          destination: account-created_event
          group: ${spring.application.name}
          content-type: application/json
        customerCreated-in-0:
          destination: customer-created_event
          group: ${spring.application.name}
          content-type: application/json
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    path: /
    enabled: ${SPRINGDOC_ENABLED:false}